### ISSUE TITLE
RR7 -useQueryState() yields  Error: useNavigate() may be used only in the context of a <Router> component. 

### ISSUE THREAD

**Issue by ZipBrandon** [47ng/nuqs#831] opened 2024-12-29 15:58 UTC
## Context

What's your version of `nuqs`?

```
"nuqs": "2.3.0-beta.2",
```

What framework are you using?

- ✅ React Router

Which version of your framework are you using?

```
    "@react-router/node": "^7.1.1",
    "@react-router/serve": "^7.1.1",
    "react-router": "^7.1.1"
    "@react-router/dev": "^7.1.1",
```

## Description

Error: useNavigate() may be used only in the context of a <Router> component. This comes from use of useQueryState.

## Reproduction
https://github.com/ZipBrandon/rr7-nuqs

Example: Steps to reproduce the behavior:

1. `npm i && npm run dev`
2. Open the browser and get met with the error (which comes from use of useQueryState in welcome.tsx.

**Comment by franky47** [comment] 2024-12-29 16:32
Thanks for the repro! It's weird because it's the exact same setup that I have in the e2e tests for RRv7, and I don't see this message there.

I'll take a closer look tonight.

**Comment by franky47** [comment] 2024-12-29 20:59
I followed your instructions, and I cannot reproduce the error:

![CleanShot 2024-12-29 at 20 59 21@2x](https://github.com/user-attachments/assets/628a9a37-f1c2-43b0-9766-2f6da0dda980)

**Comment by ZipBrandon** [comment] 2024-12-29 22:00
@franky47 Ahh, I'm using Node v22.12.0.  I installed Node 20 and it works.  Node 22+ is broken.  It seems this is upstream https://github.com/remix-run/react-router/issues/12475 .  I installed Node v22.9.0 as in the reporter and it works as expected.

**Comment by franky47** [comment] 2024-12-29 22:04
Confirmed, I was running Node.js 22.11.0, which works. Switching to 22.12.0 shows the error message.

Going to close this since this is an upstream issue in React Router, thanks for figuring it out!

**Closed by franky47** 2024-12-29 22:04 UTC
Labels: bug, cannot-reproduce, adapters/react-router
