### ISSUE TITLE
Twice render on update `useQueryStates's` field

### ISSUE THREAD

**Issue by Kavan72** [47ng/nuqs#516] opened 2024-03-03 06:50 UTC
## Context

What's your version of `nuqs`?

```
"nuqs": "^1.17.1"
```

Next.js information (obtained by running `next info`):

```
Operating System:
  Platform: linux
  Arch: x64
  Version: #107~20.04.1-Ubuntu SMP Fri Feb 9 14:20:11 UTC 2024
Binaries:
  Node: 18.19.1
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 8.9.2
Relevant Packages:
  next: 14.1.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

Are you using:

- ✅ The app router
- ❌ The pages router
- ❌ The `basePath` option in your Next.js config
- ✅ The experimental `windowHistorySupport` flag in your Next.js config

## Description
I'm using `useQueryStates` with multiple states, when i update any state using this 
```
setFilter(previousState => {
    return {
        query: query
    }
}),
```
then it's render twice, i've added one trace hook on home page to debug how many times render and which prevent the multiple render.

## Reproduction
you can find the minimal code here:- https://github.com/Kavan72/nuqs-test

**Comment by phipag** [comment] 2024-03-05 15:01
I can confirm that. It re-renders twice on Next.js 14.1.0 and only once on Next.js 14.0.4. Is this possibly related to Next.js starting to support native `window.history.pushState` methods? https://github.com/47ng/nuqs/issues/516

**Comment by phipag** [comment] 2024-03-05 15:08
I understand. Is `useSearchParams` used internally in `nuqs`? I don't use it anywhere in my code.

**Comment by franky47** [comment] 2024-03-05 15:15
Yes, it's used internally to obtain the search params during SSR for dynamic pages, and at mount time when rendering client-side.

**Comment by phipag** [comment] 2024-03-05 15:24
Got it. I just tested using `useSearchParams` as single "source of truth" for the state and the UI feels less "snappy" because it re-loads the full page before applying the state change in the query params. 

Do you have a plan/idea for `nuqs` to support this new behavior of Next.js with a single re-render like for Next.js `<=14.04`?

**Comment by franky47** [comment] 2024-03-05 15:40
> it re-loads the full page before applying the state change in the query params.

That sounds like a bug, you should try using the latest `next@14.1.2` which was published yesterday, it includes a fix for full-page reloads when combined with fragment anchor tags (see #498).

The whole "mental model" as @tordans mentioned in #408 needs to be laid out in the docs, with possible escape hatches to accommodate for various rendering patterns. Having an option to control what state is updated when would be a nice feature.

The issue becomes retro-compatibility with older versions of Next.js and the app/pages router behaviour differences, there are already a lot of hacks in place to make sure it all works fine. I've been considering dropping support for older Next.js versions in `nuqs@^2`, to remove those hacks and focus on making it future proof. Compatibility for the version range where shallow routing was in flux (14.0.2 to 14.1.1 included) will definitely be dropped, as there are contradictory behaviours which `nuqs` only supports through version detection. It's a matter of knowing what to do for 13.1.x to 14.0.1.

**Comment by phipag** [comment] 2024-03-05 16:06
>That sounds like a bug, you should try using the latest next@14.1.2 which was published yesterday

I mis-explained. It is not doing a hard reload but rather re-renders the page on the client-side (shows in XHR network requests in browser). Not a bug but expected for `router.push` from `next/navigation`, right?

Thanks for the explanation. A clarification of this would indeed be nice because it might confuse users (like me) why multiple re-renders occur when updating query state.

**Comment by Kavan72** [comment] 2024-03-05 16:20
@franky47 @phipag i just pushed the updated version of next.js to `14.1.2`, seems like issue is there, also update on my repo https://github.com/Kavan72/nuqs-test

**Comment by phipag** [comment] 2024-03-06 10:20
@Kavan72 I don't think this behavior is changed in Next.js `4.1.0` vs. `4.1.2`. As @franky47 explained, two re-renders are expected for all Next.js versions which support the native `window.history.push` operation. The first re-render will update the internal state of `nuqs` and the second re-render is caused by the Next.js `useSearchParams` hook picking up the change of the browser URL. 

As I understand it, updating the internal state first will make the UI feel quicker because it does not block until the browser URL is updated.

**Comment by Kavan72** [comment] 2024-03-06 12:46
@phipag okay thanks for clarification, btw i've found one more interesting bug, suppose i've 3 states 

```tsx
export const FilterType = {
    query: parseAsString.withDefault(''),
    leadStatus: customParseAsArrayOf(parseAsString).withDefault(['CONFIRMED', 'QUALIFIED', 'PENDING']),
    withRecognizedTerms: parseAsBoolean.withDefault(true)
}

export default function Home() {

    const [filters, setFilter] = useQueryStates(FilterType, {
        clearOnDefault: true,
    })

    useEffect(() => {
        console.log(filters)
    }, [filters.query, filters.leadStatus]);

    return (
        <Test filters={filters} setFilter={setFilter}/>
    );
}
```
if i update `query` state then `useEffect` will call once but if i update `leadStatus` which is array state then `useEffect` will call twice

**Comment by Kavan72** [comment] 2024-03-06 18:16
@franky47 can we create some kind of unique hash to useEffect and have some parser for state and url 🤔

**Comment by franky47** [comment] 2024-03-06 18:33
You don't need a hash:

```ts
useEffect(() => {},  [JSON.stringify(state)])
```

**Comment by franky47** [comment] 2024-03-06 18:35
You don't need a hash:

```ts
useEffect(() => {},  [JSON.stringify(state)])
```

**Comment by Kavan72** [comment] 2024-03-07 05:52
@franky47, I understand your point, but my question is: can't we use the same reference to update non-primitive data types to avoid this problem? I'm fine with using JSON.stringify for non-primitive data types; I just want to improve this library as much as we can 😊.

**Comment by franky47** [comment] 2024-03-21 19:30
I did some experiments with a client-side cache of state references (keyed by the serialized search param string), which works fine to ensure referential stability for updates, but it breaks upon reloading the page when that cache gets rebuilt, so it's not super reliable.

**Comment by franky47** [comment] 2024-09-12 15:35
PSA: `nuqs@1.19.1` was released with a fix for this issue. Non-primitive states (arrays, objects etc) are now referentially stable when their values don't change. This will help reducing the amount of unnecessary useEffect re-runs.

Note that this does not prevent re-renders, unfortunately one side-effect of depending on Next.js' `useSearchParams` is that it re-renders anytime _any_ search param changes.

**Closed by franky47** 2024-09-12 15:35 UTC
Labels: bug

**Comment by phipag** [comment] 2024-09-12 15:54
Thanks, I will test this soon.
